C23 compatibility
In C23, empty paramter list in function declaration actually means that
function takes parameters. Update to declare parameters for all
functions that take them, and pass NULL as needed.

Without this change, building with C23 fails with errors like shown
below. These broke build for Fedora 42, which comes with GCC 15 and
uses C23 by default.

    vikaggregatelayer.c: In function ‘vik_aggregate_layer_create’:
    vikaggregatelayer.c:631:27: error: too many arguments to function ‘vik_aggregate_layer_new’; expected 0, have 1
      631 |   VikAggregateLayer *rv = vik_aggregate_layer_new (vp);
          |                           ^~~~~~~~~~~~~~~~~~~~~~~  ~~
    In file included from viking.h:57:
    vikaggregatelayer.h:48:20: note: declared here
       48 | VikAggregateLayer *vik_aggregate_layer_new ();
          |                    ^~~~~~~~~~~~~~~~~~~~~~~
    vikaggregatelayer.c: In function ‘aggregate_layer_unmarshall’:
    vikaggregatelayer.c:680:27: error: too many arguments to function ‘vik_aggregate_layer_new’; expected 0, have 1
      680 |   VikAggregateLayer *rv = vik_aggregate_layer_new(vvp);
          |                           ^~~~~~~~~~~~~~~~~~~~~~~ ~~~
    vikaggregatelayer.h:48:20: note: declared here
       48 | VikAggregateLayer *vik_aggregate_layer_new ();
          |                    ^~~~~~~~~~~~~~~~~~~~~~~
    vikaggregatelayer.c: At top level:
    vikaggregatelayer.c:700:20: error: conflicting types for ‘vik_aggregate_layer_new’; have ‘VikAggregateLayer *(VikViewport *)’ {aka ‘struct _VikAggregateLayer *(struct _VikViewport *)’}
      700 | VikAggregateLayer *vik_aggregate_layer_new (VikViewport *vvp)
          |                    ^~~~~~~~~~~~~~~~~~~~~~~
    vikaggregatelayer.h:48:20: note: previous declaration of ‘vik_aggregate_layer_new’ with type ‘VikAggregateLayer *(void)’ {aka ‘struct _VikAggregateLayer *(void)’}
       48 | VikAggregateLayer *vik_aggregate_layer_new ();
          |                    ^~~~~~~~~~~~~~~~~~~~~~~